import Head from "next/head";
import Image from "next/image";
import WebcamCapture from "../components/WebcamCapture";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Snapchat</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1>Let's Build Snapchat</h1>

			<WebcamCapture />
		</div>
	);
}
